### ISSUE TITLE
"<</script>>" sequences in JS resources break browser HTML parser

### ISSUE THREAD

**Issue by aimozg** [tmedwards/tweego#46]
**Describe the bug**
`</script>` character sequences that occur in JS resources break browser HTML parser, as they are treated as closing tags for `<script role="script" id="twine-user-script" type="text/twine-javascript">`, destroying any following content.

**To Reproduce**
Compile a Tweego+SugarCube2 project with a JS file containing
```js
Wikifier.wikifyEval("<<script>> console.log('It works!') <</script>>");
```

**Desktop (please complete the following information):**
 - Tweego 2.1.1+81d1d71
 - SugarCube 2.36.1

**Additional context**
I don't think it's even possible to escape these at Tweego level (see [Restrictions for contents of script elements](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements)).

**Comment by tmedwards** [comment]
This is a browser issue, neither a Tweego nor a SugarCube issue.

Parsing of HTML `<script>` tag contents in the browser is probably not what most people expect/want due to historical issues that are never going to be changed.  Thus, using the `<<script>>` macro within a `<script>` tag isn't going to work as you'd hope either.

That said.  Why are you even attempting to use the `<<script>>` macro, which executes JavaScript, within your Story JavaScript, which exists to execute JavaScript?

*(Closing this as not a Tweego issue, but feel free to continue the discussion until we get your situation straightened out.)*

**Comment by aimozg** [comment]
> This is a browser issue, neither a Tweego nor a SugarCube issue.

Tweego escapes `<>` in passages, and if it were possible to do same for `</script>` it should do it. But from what I understand, it is impossible (cannot escape token, only split, and that requires knowledge of JS context which is definitely not Tweego responsibility). 

Still posted the issue in case you have ideas. The only I can think of is to emit a different tag than `<script>` with `&`-escaped 
characters, but that needs checking with the story format code and is an overkill for such an rare case.

> That said. Why are you even attempting to use the <<script>> macro, which executes JavaScript, within your Story JavaScript, which exists to execute JavaScript?

Generated code, SugarCube partially transpiled to JS (for performance and early syntax error detection). Contents of `<<script>>` are injected as-is, but when `<<script>>` is inside a block macro that is not supported by the transpiler, the whole block is sent to wikifier.

**Comment by tmedwards** [comment]
> Tweego escapes `<>` in passages, and if it were possible to do same for `</script>` it should do it.

Twine-ecosystem compilers encode special characters within passages specifically to avoid early processing by browsers.  Story formats decode said characters, generally on-the-fly when reading passage contents.

Your problem is not specifically related to that, nor can it be solved by that.  Your problem comes from when the decoded Story JavaScript passage content is injected into the page `<head>` as a `<script>` element.


&nbsp;
> Generated code, SugarCube partially transpiled to JS (for performance and early syntax error detection). Contents of <<script>> are injected as-is, but when <<script>> is inside a block macro that is not supported by the transpiler, the whole block is sent to wikifier.

Oy vey.

The easiest thing would likely be have your transpiler do one of the following:

1. String shenanigans of some sort, so that the problemattic sequence doesn't exist until the code is processed by the JavaScript engine.  E.g., changing `"…<</script>>…"` to `"…<<"+"/script>>…"`.
2. Rename the macro.  E.g., change `<<script>><</script>>` to `<<jscript>><</jscript>>`.

The latter does require you to create an alias for `<<script>>`, but that's easily done via the `Macro`API.  E.g., place something like the following at the top of your JavaScript, `Macro.add('jscript', 'script');`.
